apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverse-shell
spec:
  selector:
    matchLabels:
      app: reverse-shell
  replicas: 2
  template:
    metadata:
      labels:
        app: reverse-shell
    spec:
      containers:
      - name: openssh-server
        image: linuxserver/openssh-server:version-8.8_p1-r1
        imagePullPolicy: Always
        ports:
        - containerPort: 2222
        readinessProbe:
          tcpSocket:
            port: 2222
          initialDelaySeconds: 5
          periodSeconds: 10
        securityContext:
          allowPrivilegeEscalation: false
        stdin: true
        tty: true
        env:
        - name: USER_NAME
          value: "ssekula"
        - name: PASSWORD_ACCESS
          value: true
        - name: USER_PASSWORD
          value: "TestPassword.123"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
     

