apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverse-shell
spec:
  selector:
    matchLabels:
      app: reverse-shell
  replicas: 2
  template:
    metadata:
      labels:
        app: reverse-shell
    spec:
      containers:
      - name: netcat
        image: chilcano/netcat:jessie
        imagePullPolicy: Always
        ports:
        - containerPort: 8888
        securityContext:
          allowPrivilegeEscalation: false
        stdin: true
        tty: true
        command: ['/bin/nc', '-vvl', '1337', '-p', '8888']
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
     
